### ISSUE TITLE
Default rcon

### ISSUE THREAD

**Issue by HelderFSFerreira** [Gonzih/docker-csgo-server#1]
How can i add an rcon password?
If i access the container i don't have permitions to download an program to edit like vim or nano...

**Comment by Gonzih** [comment]
You can just do "echo 'rcon_password mypassword' >> $SERVER/csgo/csgo/cfg/server.cfg" when you are inside the container (using `docker exec` for example). Or add this line to the dockerfile. You can also create your own Dockerfile, use this image as a base `FROM csgoserver` and add `RUN echo ....` command in there or modify original Dockerfile for a server.
