### ISSUE TITLE
Missing Library Error

### ISSUE THREAD

**Issue by sparticvs** [Gonzih/docker-csgo-server#11]
I'm not entirely sure I understand how this happened, but there seems to now be an error. This is recent, within the last couple weeks.

`Failed to open dedicated.so (libstdc++.so.6: cannot open shared object file: No such file or directory)`

Thoughts on what may be causing this? It's in the `./linux32/` directory.

**Comment by Gonzih** [comment]
Try adding `apt-get -y install libstdc++6` to the dockerfile. Tell me if this help.

**Comment by mrfoyl** [comment]
That works. It's implemented in my fork. My fork also has ebot integration. feel free to use my docker-compose.yml file :)

**Comment by sparticvs** [comment]
Thanks folks for looking at this. Sorry I didn't have a chance to test (work got suddenly busy). I'll report back if I see any other issues, thanks for updating.

**Comment by sparticvs** [comment]
Not to be a nuisance, would it be possible to push the new Dockerfile to Docker Hub?

**Comment by Gonzih** [comment]
Docker hub did not rebuild the image automatically for some reason. I will
take a look at this.

**Comment by Gonzih** [comment]
@sparticvs image was updated by docker hub build system, please try to pull now.

**Comment by sparticvs** [comment]
Thanks @Gonzih . It doesn't look like the image from Docker Hub works, same error. I have time later today to do additional diagnostics. I will take a look then and see what is happening.

**Comment by Gonzih** [comment]
I queued another build in docker hub, for some reason docker hub stopped doing automatic builds on every push.
