### ISSUE TITLE
Tried downloading and first start can't find steamclient.so

### ISSUE THREAD

**Issue by scarlsoniGT** [Gonzih/docker-csgo-server#13]
On first startup I encountered (Sorry for the format.. don't know how to turn off markdown)

`
Setting breakpad minidump AppID = 740
Using breakpad crash handler
Forcing breakpad minidump interfaces to load
dlopen failed trying to load:
/home/csgo/.steam/sdk32/steamclient.so
with error:
/home/csgo/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
LD_LIBRARY_PATH=/home/csgo/hlserver/csgo/bin:/home/csgo/hlserver/csgo:/home/csgo/hlserver/csgo/bin:
`

Along with a few others that probably aren't important in the log.  I've never stood up any CS servers beffoere so I'm slow at debugging.  any help is appreciated.  I'll contribute if I find anything.

`
csgo/srcds_run: 32: csgo/srcds_run: pushd: not found
csgo/srcds_run: 35: csgo/srcds_run: popd: not found
Server will auto-restart if there is a crash.
Updating server using Steam.
----------------------------
***************************************************
The recommended way to run steamcmd is: steamcmd.sh +runscript /home/csgo/hlserver/csgo_ds.txt
***************************************************
Redirecting stderr to '/home/csgo/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/csgo/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
login anonymous

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
force_install_dir ./csgo
app_update 740 validate
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 7.68 (45307398 / 589946078)
 Update state (0x61) downloading, progress: 28.69 (169272638 / 589946078)
 Update state (0x61) downloading, progress: 47.40 (279615783 / 589946078)
 Update state (0x61) downloading, progress: 68.17 (402178911 / 589946078)
 Update state (0x61) downloading, progress: 85.28 (503116098 / 589946078)
 Update state (0x61) downloading, progress: 98.65 (582008639 / 589946078)
 Update state (0x101) committing, progress: 0.00 (0 / 589946078)
Success! App '740' fully installed.
quit
----------------------------
Setting breakpad minidump AppID = 740
Using breakpad crash handler
Forcing breakpad minidump interfaces to load
dlopen failed trying to load:
/home/csgo/.steam/sdk32/steamclient.so
with error:
/home/csgo/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
LD_LIBRARY_PATH=/home/csgo/hlserver/csgo/bin:/home/csgo/hlserver/csgo:/home/csgo/hlserver/csgo/bin:
#
#Console initialized.
#Using breakpad minidump system 740/13629.658.DC
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Game.dll loaded for "Counter-Strike: Global Offensive"
#CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
#CGameEventManager::AddListener: event 'game_newmap' unknown.
#CGameEventManager::AddListener: event 'finale_start' unknown.
#CGameEventManager::AddListener: event 'round_start' unknown.
#CGameEventManager::AddListener: event 'round_end' unknown.
#CGameEventManager::AddListener: event 'difficulty_changed' unknown.
#CGameEventManager::AddListener: event 'player_connect' unknown.
#CGameEventManager::AddListener: event 'player_disconnect' unknown.
#GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
#GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
#GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
Particles: Missing 'particles/money_fx.pcf'
No web api auth key specified - workshop downloads will be disabled.
maxplayers set to 64
ConVarRef cl_embedded_stream_video_playing doesn't point to an existing ConVar
Unknown command "cl_bobamt_vert"
Unknown command "cl_bobamt_lat"
Unknown command "cl_bob_lower_amt"
Unknown command "cl_viewmodel_shift_left_amt"
Unknown command "cl_viewmodel_shift_right_amt"
Unknown command "cl_teamid_min"
Unknown command "cl_teamid_max"
Unknown command "cl_teamid_overhead"
Unknown command "cl_teamid_overhead_maxdist"
Server logging enabled.
Server logging data to file logs/L000_000_000_000_0_201803050153_000.log
L 03/05/2018 - 01:53:01: Log file started (file "logs/L000_000_000_000_0_201803050153_000.log") (game "/home/csgo/hlserver/csgo/csgo") (version "6974")
Setting mapgroup to 'mg_active'
Network: IP 172.17.0.2 ---- Host_NewGame ----
L 03/05/2018 - 01:53:01: Log file closed
Server logging data to file logs/L172_017_000_002_27015_201803050153_000.log
L 03/05/2018 - 01:53:01: Log file started (file "logs/L172_017_000_002_27015_201803050153_000.log") (game "/home/csgo/hlserver/csgo/csgo") (version "6974")
L 03/05/2018 - 01:53:01: Loading map "de_cache"
L 03/05/2018 - 01:53:01: server cvars start
L 03/05/2018 - 01:53:01: "cash_player_killed_teammate" = "-300"
L 03/05/2018 - 01:53:01: "cash_player_respawn_amount" = "0"
L 03/05/2018 - 01:53:01: "sv_maxspeed" = "320"
L 03/05/2018 - 01:53:01: "cash_team_rescued_hostage" = "0"
L 03/05/2018 - 01:53:01: "cash_team_win_by_defusing_bomb" = "3250"
L 03/05/2018 - 01:53:01: "sv_rollangle" = "0"
L 03/05/2018 - 01:53:01: "r_AirboatViewZHeight" = "0.0"
L 03/05/2018 - 01:53:01: "sv_cheats" = "0"
L 03/05/2018 - 01:53:01: "r_VehicleViewDampen" = "1"
L 03/05/2018 - 01:53:01: "mp_allowNPCs" = "1"
L 03/05/2018 - 01:53:01: "mp_tournament" = "0"
L 03/05/2018 - 01:53:01: "sv_vote_issue_pause_match_spec_only" = "0"
L 03/05/2018 - 01:53:01: "sv_spec_hear" = "1"
L 03/05/2018 - 01:53:01: "cash_player_interact_with_hostage" = "150"
L 03/05/2018 - 01:53:01: "mp_maxrounds" = "0"
L 03/05/2018 - 01:53:01: "mp_flashlight" = "0"
L 03/05/2018 - 01:53:01: "sv_tags" = ""
L 03/05/2018 - 01:53:01: "sv_stepsize" = "18"
L 03/05/2018 - 01:53:01: "sv_alltalk" = "0"
L 03/05/2018 - 01:53:01: "mp_teamlist" = "hgrunt;scientist"
L 03/05/2018 - 01:53:01: "mp_footsteps" = "1"
L 03/05/2018 - 01:53:01: "sv_noclipaccelerate" = "5"
L 03/05/2018 - 01:53:01: "sv_accelerate_debug_speed" = "0"
L 03/05/2018 - 01:53:01: "sv_wateraccelerate" = "10"
L 03/05/2018 - 01:53:01: "mp_stalemate_enable" = "0"
L 03/05/2018 - 01:53:01: "mp_autocrosshair" = "1"
L 03/05/2018 - 01:53:01: "cash_team_elimination_bomb_map" = "3250"
L 03/05/2018 - 01:53:01: "cash_player_get_killed" = "0"
L 03/05/2018 - 01:53:01: "mp_roundtime_defuse" = "0"
L 03/05/2018 - 01:53:01: "sv_autobuyammo" = "0"
L 03/05/2018 - 01:53:01: "sv_rollspeed" = "200"
L 03/05/2018 - 01:53:01: "sv_airaccelerate" = "12"
L 03/05/2018 - 01:53:01: "sv_show_team_equipment_prohibit" = "0"
L 03/05/2018 - 01:53:01: "mp_teams_unbalance_limit" = "1"
L 03/05/2018 - 01:53:01: "mp_timelimit" = "5"
L 03/05/2018 - 01:53:01: "cash_team_loser_bonus" = "1400"
L 03/05/2018 - 01:53:01: "sv_deadtalk" = "0"
L 03/05/2018 - 01:53:01: "cash_player_rescued_hostage" = "1000"
L 03/05/2018 - 01:53:01: "sv_waterfriction" = "1"
L 03/05/2018 - 01:53:01: "sv_competitive_official_5v5" = "0"
L 03/05/2018 - 01:53:01: "sv_steamgroup" = ""
L 03/05/2018 - 01:53:01: "cash_player_killed_enemy_default" = "300"
L 03/05/2018 - 01:53:01: "coop" = "0"
L 03/05/2018 - 01:53:01: "mp_respawnwavetime" = "10.0"
L 03/05/2018 - 01:53:01: "sv_teamid_overhead" = "1"
L 03/05/2018 - 01:53:01: "tv_enable1" = "0"
L 03/05/2018 - 01:53:01: "nextlevel" = ""
L 03/05/2018 - 01:53:01: "sv_stopspeed" = "80"
L 03/05/2018 - 01:53:01: "sv_specaccelerate" = "5"
L 03/05/2018 - 01:53:01: "deathmatch" = "1"
L 03/05/2018 - 01:53:01: "tv_enable" = "0"
L 03/05/2018 - 01:53:01: "mp_roundtime_hostage" = "0"
L 03/05/2018 - 01:53:01: "mp_freezetime" = "6"
L 03/05/2018 - 01:53:01: "mp_teammates_are_enemies" = "0"
L 03/05/2018 - 01:53:01: "mp_falldamage" = "0"
L 03/05/2018 - 01:53:01: "sv_accelerate_use_weapon_speed" = "1"
L 03/05/2018 - 01:53:01: "sv_voiceenable" = "1"
L 03/05/2018 - 01:53:01: "sv_teamid_overhead_always_prohibit" = "0"
L 03/05/2018 - 01:53:01: "sv_bounce" = "0"
L 03/05/2018 - 01:53:01: "mp_disable_respawn_times" = "0"
L 03/05/2018 - 01:53:01: "r_AirboatViewDampenFreq" = "7.0"
L 03/05/2018 - 01:53:01: "mp_weaponstay" = "0"
L 03/05/2018 - 01:53:01: "mp_hostagepenalty" = "10"
L 03/05/2018 - 01:53:01: "tv_advertise_watchable" = "0"
L 03/05/2018 - 01:53:01: "mp_friendlyfire" = "0"
L 03/05/2018 - 01:53:01: "cash_team_hostage_interaction" = "500"
L 03/05/2018 - 01:53:01: "sv_noclipspeed" = "5"
L 03/05/2018 - 01:53:01: "cash_team_win_by_time_running_out_bomb" = "3250"
L 03/05/2018 - 01:53:01: "sv_allchat" = "1"
L 03/05/2018 - 01:53:01: "mp_buy_during_immunity" = "0"
L 03/05/2018 - 01:53:01: "cash_player_killed_enemy_factor" = "1"
L 03/05/2018 - 01:53:01: "mp_c4timer" = "40"
L 03/05/2018 - 01:53:01: "r_JeepViewDampenDamp" = "1.0"
L 03/05/2018 - 01:53:01: "sv_competitive_minspec" = "1"
L 03/05/2018 - 01:53:01: "r_AirboatViewDampenDamp" = "1.0"
L 03/05/2018 - 01:53:01: "sv_max_allowed_net_graph" = "1"
L 03/05/2018 - 01:53:01: "mp_stalemate_at_timelimit" = "0"
L 03/05/2018 - 01:53:01: "mp_limitteams" = "2"
L 03/05/2018 - 01:53:01: "sv_footsteps" = "1"
L 03/05/2018 - 01:53:01: "sv_vote_issue_kick_allowed" = "1"
L 03/05/2018 - 01:53:01: "cash_team_survive_guardian_wave" = "1000"
L 03/05/2018 - 01:53:01: "tv_relaypassword" = ""
L 03/05/2018 - 01:53:01: "mp_teamplay" = "0"
L 03/05/2018 - 01:53:01: "cash_team_terrorist_win_bomb" = "3500"
L 03/05/2018 - 01:53:01: "cash_team_elimination_hostage_map_t" = "1000"
L 03/05/2018 - 01:53:01: "r_JeepViewDampenFreq" = "7.0"
L 03/05/2018 - 01:53:01: "cash_team_win_by_time_running_out_hostage" = "3250"
L 03/05/2018 - 01:53:01: "sv_specnoclip" = "1"
L 03/05/2018 - 01:53:01: "sv_friction" = "5.2"
L 03/05/2018 - 01:53:01: "cash_player_bomb_planted" = "300"
L 03/05/2018 - 01:53:01: "mp_autoteambalance" = "1"
L 03/05/2018 - 01:53:01: "sv_contact" = ""
L 03/05/2018 - 01:53:01: "sv_vote_kick_ban_duration" = "15"
L 03/05/2018 - 01:53:01: "cash_player_bomb_defused" = "300"
L 03/05/2018 - 01:53:01: "mp_roundtime" = "5"
L 03/05/2018 - 01:53:01: "sv_kick_ban_duration" = "15"
L 03/05/2018 - 01:53:01: "cash_team_planted_bomb_but_defused" = "800"
L 03/05/2018 - 01:53:01: "cash_player_killed_hostage" = "-1000"
L 03/05/2018 - 01:53:01: "sv_vote_issue_loadbackup_allowed" = "1"
L 03/05/2018 - 01:53:01: "nextmode" = ""
L 03/05/2018 - 01:53:01: "mp_fraglimit" = "0"
L 03/05/2018 - 01:53:01: "mp_forcerespawn" = "1"
L 03/05/2018 - 01:53:01: "mp_winlimit" = "0"
L 03/05/2018 - 01:53:01: "sv_accelerate" = "5.5"
L 03/05/2018 - 01:53:01: "mp_buy_anywhere" = "0"
L 03/05/2018 - 01:53:01: "sv_gravity" = "800"
L 03/05/2018 - 01:53:01: "sv_password" = ""
L 03/05/2018 - 01:53:01: "cash_team_elimination_hostage_map_ct" = "2000"
L 03/05/2018 - 01:53:01: "cash_team_win_by_hostage_rescue" = "3500"
L 03/05/2018 - 01:53:01: "sv_vote_issue_loadbackup_spec_only" = "0"
L 03/05/2018 - 01:53:01: "cash_team_loser_bonus_consecutive_rounds" = "500"
L 03/05/2018 - 01:53:01: "cash_player_damage_hostage" = "-30"
L 03/05/2018 - 01:53:01: "r_JeepViewZHeight" = "10.0"
L 03/05/2018 - 01:53:01: "cash_team_hostage_alive" = "0"
L 03/05/2018 - 01:53:01: "tv_password" = ""
L 03/05/2018 - 01:53:01: "sv_specspeed" = "3"
L 03/05/2018 - 01:53:01: server cvars end
ConVarRef r_staticlight_streams_indirect_only doesn't point to an existing ConVar
Warning in .VMT file ($color): no ']' or '}' found in vector key "$color".
Did you forget to surround the vector with "s?
L 03/05/2018 - 01:53:02: Started map "de_cache" (CRC "-895876686")
Host_NewGame on map de_cache
GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
ConVarRef room_type doesn't point to an existing ConVar
ammo_grenade_limit_default - 1
ammo_grenade_limit_flashbang - 1
ammo_grenade_limit_total - 3
bot_allow_grenades - 1
bot_allow_machine_guns - 1
bot_allow_pistols - 1
bot_allow_rifles - 1
bot_allow_rogues - 1
bot_allow_shotguns - 1
bot_allow_snipers - 1
bot_allow_sub_machine_guns - 1
bot_autodifficulty_threshold_high - 5.0
bot_autodifficulty_threshold_low - -2.0
bot_chatter - normal
bot_defer_to_human_goals - 0
bot_defer_to_human_items - 1
bot_difficulty - 1
bot_quota - 10
bot_quota_mode - normal
cash_player_bomb_defused - 300
cash_player_bomb_planted - 300
cash_player_damage_hostage - -30
cash_player_get_killed - 0
cash_player_interact_with_hostage - 150
cash_player_killed_enemy_default - 300
cash_player_killed_enemy_factor - 1
cash_player_killed_hostage - -1000
cash_player_killed_teammate - -300
cash_player_rescued_hostage - 1000
cash_player_respawn_amount - 0
cash_team_elimination_bomb_map - 3250
cash_team_elimination_hostage_map_ct - 2000
cash_team_elimination_hostage_map_t - 1000
cash_team_hostage_alive - 0
cash_team_hostage_interaction - 500
cash_team_loser_bonus - 1400
cash_team_loser_bonus_consecutive_rounds - 500
cash_team_planted_bomb_but_defused - 800
cash_team_rescued_hostage - 0
cash_team_survive_guardian_wave - 1000
cash_team_terrorist_win_bomb - 3500
cash_team_win_by_defusing_bomb - 3250
cash_team_win_by_hostage_rescue - 3500
cash_team_win_by_time_running_out_bomb - 3250
cash_team_win_by_time_running_out_hostage - 3250
ff_damage_reduction_bullets - 0.1
ff_damage_reduction_grenade - 0.25
ff_damage_reduction_grenade_self - 1
ff_damage_reduction_other - 0.25
global_chatter_info -
mp_afterroundmoney - 0
mp_anyone_can_pickup_c4 - 0
mp_autoteambalance - 1
mp_buy_allow_grenades - 1
mp_buy_allow_guns - 255
mp_buy_anywhere - 0
mp_buy_during_immunity - 0
mp_buytime - 90
mp_c4_cannot_be_defused - 0
mp_c4timer - 40
mp_consecutive_loss_max - 4
mp_coop_force_join_ct - 0
mp_coopmission_bot_difficulty_offset - 0
mp_coopmission_mission_number - 0
mp_ct_default_grenades -
mp_ct_default_melee - weapon_knife
mp_ct_default_primary -
mp_ct_default_secondary - weapon_hkp2000
mp_damage_headshot_only - 0
mp_damage_scale_ct_body - 1.0
mp_damage_scale_ct_head - 1.0
mp_damage_scale_t_body - 1.0
mp_damage_scale_t_head - 1.0
mp_damage_vampiric_amount - 0
mp_death_drop_c4 - 1
mp_death_drop_defuser - 1
mp_death_drop_grenade - 2
mp_death_drop_gun - 1
mp_deathcam_skippable - 1
mp_default_team_winner_no_objective - -1
mp_defuser_allocation - 0
mp_display_kill_assists - 1
mp_dm_bonus_percent - 50
mp_dm_bonus_respawn - 0
mp_dm_bonusweapon_dogtags - 0
mp_dm_dogtag_score - 0
mp_dm_kill_base_score - 10
mp_dm_teammode - 0
mp_dm_teammode_bonus_score - 1
mp_dm_teammode_dogtag_score - 0
mp_dm_teammode_kill_score - 1
mp_dogtag_despawn_on_killer_death - 1
mp_dogtag_despawn_time - 120
mp_dogtag_pickup_rule - 0
mp_economy_reset_rounds - 0
mp_equipment_reset_rounds - 0
mp_force_assign_teams - 0
mp_force_pick_time - 15
mp_forcecamera - 1
mp_free_armor - 0
mp_freezetime - 6
mp_friendlyfire - 0
mp_ggprogressive_round_restart_delay - 15.0
mp_ggtr_always_upgrade - 0
mp_ggtr_bomb_defuse_bonus - 1
mp_ggtr_bomb_detonation_bonus - 1
mp_ggtr_bomb_pts_for_flash - 4
mp_ggtr_bomb_pts_for_he - 3
mp_ggtr_bomb_pts_for_molotov - 5
mp_ggtr_bomb_pts_for_upgrade - 2.0
mp_ggtr_bomb_respawn_delay - 0.0
mp_ggtr_end_round_kill_bonus - 1
mp_ggtr_halftime_delay - 0.0
mp_ggtr_last_weapon_kill_ends_half - 0
mp_give_player_c4 - 1
mp_global_damage_per_second - 0.0
mp_guardian_bot_money_per_wave - 800
mp_guardian_loc_adjective -
mp_guardian_loc_condition -
mp_guardian_loc_icon -
mp_guardian_loc_mission - default
mp_guardian_loc_override -
mp_guardian_loc_weapon -
mp_guardian_player_dist_max - 2000
mp_guardian_player_dist_min - 1300
mp_guardian_special_kills_needed - 10
mp_guardian_special_weapon_needed - awp
mp_guardian_target_site - -1
mp_halftime - 0
mp_halftime_pausetimer - 0
mp_heavyassaultsuit_cooldown - 5
mp_hostagepenalty - 10
mp_hostages_max - 2
mp_hostages_spawn_force_positions -
mp_hostages_spawn_same_every_round - 1
mp_items_prohibited -
mp_limitteams - 2
mp_match_can_clinch - 1
mp_max_armor - 2
mp_maxmoney - 16000
mp_maxrounds - 0
mp_molotovusedelay - 15.0
mp_playercashawards - 1
mp_radar_showall - 0
mp_randomspawn - 0
mp_randomspawn_dist - 0
mp_randomspawn_los - 1
mp_respawn_immunitytime - 4.0
mp_respawn_on_death_ct - 0
mp_respawn_on_death_t - 0
mp_respawnwavetime_ct - 10.0
mp_respawnwavetime_t - 10.0
mp_round_restart_delay - 7.0
mp_roundtime - 5
mp_roundtime_defuse - 0
mp_roundtime_hostage - 0
mp_solid_teammates - 1
mp_starting_losses - 0
mp_startmoney - 800
mp_t_default_grenades -
mp_t_default_melee - weapon_knife
mp_t_default_primary -
mp_t_default_secondary - weapon_glock
mp_taser_recharge_time - -1
mp_teamcashawards - 1
mp_teammates_are_enemies - 0
mp_timelimit - 5
mp_use_respawn_waves - 0
mp_warmup_pausetimer - 0
mp_warmuptime - 30
mp_warmuptime_all_players_connected - 0
mp_weapon_self_inflict_amount - 0
mp_weapons_allow_heavy - -1
mp_weapons_allow_heavyassaultsuit - 0
mp_weapons_allow_map_placed - 0
mp_weapons_allow_pistols - -1
mp_weapons_allow_rifles - -1
mp_weapons_allow_smgs - -1
ConVarRef mp_weapons_allow_tagrenade doesn't point to an existing ConVar
mp_weapons_allow_typecount - 5
mp_weapons_allow_zeus - 1
mp_weapons_glow_on_ground - 0
mp_weapons_max_gun_purchases_per_weapon_per_match - -1
mp_heavyassaultsuit_speed - 130
mp_heavyassaultsuit_deploy_timescale - 0.8
mp_heavyassaultsuit_aimpunch - 1.0
mp_heavybot_damage_reduction_scale - 1.0
mp_win_panel_display_time - 3
occlusion_test_async - 0
spec_freeze_panel_extended_time - 0.0
spec_freeze_time - 3.0
spec_replay_enable - 0
sv_accelerate - 5.5
sv_airaccelerate - 12
sv_allow_votes - 1
sv_alltalk - 0
sv_arms_race_vote_to_restart_disallowed_after - 0
sv_auto_adjust_bot_difficulty - 1
sv_auto_full_alltalk_during_warmup_half_end - 1
sv_autobunnyhopping - 0
sv_autobuyammo - 0
sv_bot_buy_decoy_weight - 1
sv_bot_buy_flash_weight - 1
sv_bot_buy_grenade_chance - 33
sv_bot_buy_hegrenade_weight - 6
sv_bot_buy_molotov_weight - 1
sv_bot_buy_smoke_weight - 1
sv_bots_force_rebuy_every_round - 0
sv_bots_get_easier_each_win - 0
sv_bots_get_harder_after_each_wave - 0
sv_bounce - 0
sv_buy_status_override - -1
sv_deadtalk - 0
sv_disable_show_team_select_menu - 0
sv_duplicate_playernames_ok - 0
sv_enablebunnyhopping - 0
sv_friction - 5.2
sv_gravity - 800
sv_guardian_heavy_all - 0
sv_guardian_heavy_count - 0
sv_guardian_max_wave_for_heavy - 0
sv_guardian_min_wave_for_heavy - 0
sv_ignoregrenaderadio - 0
sv_infinite_ammo - 0
sv_maxspeed - 320
sv_maxvelocity - 3500
sv_occlude_players - 1
sv_staminajumpcost - .080
sv_staminalandcost - .050
sv_stopspeed - 80
sv_talk_enemy_dead - 0
sv_talk_enemy_living - 0
sv_vote_to_changelevel_before_match_point - 0
sv_wateraccelerate - 10
sv_waterfriction - 1
tv_delay - 10
weapon_accuracy_nospread - 0
weapon_air_spread_scale - 1.0
ConVarRef weapon_cleanup_on_round_restart doesn't point to an existing [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 730
dlopen failed trying to load:
/home/csgo/.steam/sdk32/steamclient.so
with error:
/home/csgo/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Setting breakpad minidump AppID = 740
ConVar
weapon_max_before_cleanup - 0
weapon_recoil_scale - 2.0
weapon_reticle_knife_show - 0
ff_damage_reduction_grenade - 0.25
ff_damage_reduction_grenade_self - 1
ff_damage_reduction_other - 0.25
mp_friendlyfire - 0
mp_warmuptime - 30
mp_warmuptime_all_players_connected - 0
Executing dedicated server config file
Unknown command "sv_maxcmdrate"
L 03/05/2018 - 01:53:02: server_cvar: "cash_player_bomb_defused" "200"
L 03/05/2018 - 01:53:02: server_cvar: "cash_player_bomb_planted" "200"
L 03/05/2018 - 01:53:02: server_cvar: "cash_player_interact_with_hostage" "300"
L 03/05/2018 - 01:53:02: server_cvar: "cash_player_killed_enemy_default" "200"
L 03/05/2018 - 01:53:02: server_cvar: "cash_player_killed_enemy_factor" "0.5"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_elimination_bomb_map" "2700"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_elimination_hostage_map_t" "2000"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_elimination_hostage_map_ct" "2300"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_loser_bonus" "2400"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_loser_bonus_consecutive_rounds" "0"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_planted_bomb_but_defused" "200"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_terrorist_win_bomb" "2700"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_win_by_defusing_bomb" "2700"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_win_by_hostage_rescue" "3000"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_win_by_time_running_out_hostage" "2000"
L 03/05/2018 - 01:53:02: server_cvar: "cash_team_win_by_time_running_out_bomb" "2700"
L 03/05/2018 - 01:53:02: server_cvar: "mp_freezetime" "5"
L 03/05/2018 - 01:53:02: server_cvar: "mp_friendlyfire" "1"
L 03/05/2018 - 01:53:02: server_cvar: "mp_maxrounds" "15"
L 03/05/2018 - 01:53:02: server_cvar: "mp_roundtime" "3"
L 03/05/2018 - 01:53:02: server_cvar: "mp_roundtime_hostage" "2"
L 03/05/2018 - 01:53:02: server_cvar: "mp_roundtime_defuse" "2.25"
L 03/05/2018 - 01:53:02: server_cvar: "mp_timelimit" "0"
Stopping 0 worker threads
Starting 1 worker threads
1 threads. 361,325 ticks
exec: couldn't exec gamemode_casual_server.cfg
Attempted to create unknown entity type func_instance_origin!
Can't init func_instance_origin
A Door has Door model (models/de_cache/de_cache_metal_door_02.mdl) with no door_options or m_nPhysicsMaterial specified! Verify that SKIN is valid, and has a corresponding options block in the model QC file
CSoundEmitterSystemBase::GetParametersForSound:  No such sound ambient/water/drip_loop1.wav
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound weapons/molotov/fire_loop_1.wav
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
Commentary: Could not find commentary data file 'maps/de_cache_commentary.txt'.
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Initializing Steam libraries for secure Internet server
****************************************************
*                                                  *
*  No Steam account token was specified.           *
*  Logging into anonymous game server account.     *
*  Connections will be restricted to LAN only.     *
*                                                  *
*  To create a game server account go to           *
*  http://steamcommunity.com/dev/managegameservers *
*                                                  *
****************************************************
Connection to Steam servers successful.
   Public IP is 71.114.18.116.
Assigned anonymous gameserver Steam ID [A:1:823350272:9702].
VAC secure mode is activated.
GC Connection established for server ver
`

**Comment by Soren90** [comment]
I have the exact same issue. have you been able to solve it @scarlsoniGT ?

EDIT:
I've been troubleshooting this for a while and it seems like the issue shows up when i copy the autoexec.cfg to it's folder. As soon as i'm using the default config it seems to work fine.

**Comment by scarlsoniGT** [comment]
Nope, I ended up giving up and installing on the host :/

**Comment by Soren90** [comment]
You only need to remove "log on" in the autoexec.cfg and it will work.

Den tors 27 dec. 2018 19:05 skrev scarlsoniGT <notifications@github.com>:
