### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by razor-x** [Gonzih/docker-csgo-server#15]
Hi, it's really awesome you got this working in Docker! Can you please consider adding a license to this project so others who have forked this or would like to fork it have explicit permission to make derivative works? Check out https://choosealicense.com/

A simple choice would be [MIT](https://choosealicense.com/licenses/mit/) or [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/).

**Comment by Gonzih** [comment]
Added MIT license, thanks
