### ISSUE TITLE
Auto update not enable?

### ISSUE THREAD

**Issue by pauloaguiar26** [Gonzih/docker-csgo-server#16]
My server doesn't auto update.
I had to remove image and build again from the pull. Is there any command to update?

Also, how to increase maxplayers?

**Comment by Gonzih** [comment]
Try restarting running container. Start script includes app update call.

**Comment by pauloaguiar26** [comment]
Will try in the next update! What about increasing max number of players?

**Comment by Gonzih** [comment]
you can use `+maxplayers #` at the end of start command (it was deprecated, but not sure if it was removed), for more info take a look here https://gaming.stackexchange.com/questions/141495/how-can-i-change-the-maximum-number-of-players-in-my-server

**Comment by pauloaguiar26** [comment]
only the build image is updated. If csgo update we need to build a new image (download everytime csgo full size)

**Comment by Gonzih** [comment]
You can create new overlay layer that just updates your original image like so:

```Dockerfile
FROM  gonzih/csgo-server

ENV USER csgo
ENV HOME /home/$USER
ENV SERVER $HOME/hlserver

# change this date to any value, this is here to just invalidate all further layers and run update again
RUN echo update on 20-01-2020 
RUN $SERVER/update.sh

WORKDIR /home/$USER/hlserver
ENTRYPOINT ["./csgo.sh"]
CMD ["-console" "-usercon" "+game_type" "0" "+game_mode" "1" "+mapgroup" "mg_active" "+map" "de_cache"]
```
