### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by danielfilho** [Gonzih/docker-csgo-server#2]
Thanks for sharing this, I really appreciate your effort on sharing it :)

Do you have any tutorial or can recommend something where I can understand better things like: where/how to add authentication, adding mods, adding the GSLT and api keys for workshop, and so on?

**Comment by Gonzih** [comment]
So basically what you need to learn is how to work with docker. You can always just clone this repo and start modifying it. Addig mods/authentication/etc is basically copying/modifying files inside the container.
