### ISSUE TITLE
Question about run process in Dockerfile

### ISSUE THREAD

**Issue by jammsen** [Gonzih/docker-csgo-server#3]
Hey guys,
is there a reason why you dont use inline RUN commands more grouped?
I counted 8 RUN commands with basic usage, which could be moved to one single RUN command. 
A benefit of this is, your Dockerfile doesnt create 8 AUFS layers on every machine its used.
Example:
#Setup all environments
ENV var1 ... 
ENV var2 ...
ENV var3 ...
ENV var4 ...
RUN command1;command2;command3;

Greetings,
jammsen

**Comment by Gonzih** [comment]
I did minor change in dockerfile, is that what you had in mind?

**Comment by jammsen** [comment]
Wheeew yeah, 3 AUFS layers instead of 8, exactly what i meant, thanks!

**Comment by Gonzih** [comment]
Also you should not run aufs. Switch to overlay adapter.

**Comment by jammsen** [comment]
Hey do you plan to publish this script as an image on hub.docker.com?

**Comment by Gonzih** [comment]
Image is too big for that (> 13GB i think), tried to push it. It takes 
hours and often due to networking issues abort is a thing that happens.

**Comment by jammsen** [comment]
Can you add me on twitter so we can talk more in detail? @jammsen
