### ISSUE TITLE
auto-update

### ISSUE THREAD

**Issue by janstuemmel** [Gonzih/docker-csgo-server#4]
In my understanding, the csgo-server files are downloaded into a docker layer. When it comes to updating the server, every csgo-docker instance must download the update for the gameserver. To bypass this i can just rebuilt the docker image itself, is that right?

nice image btw.

greetz jan

**Comment by Gonzih** [comment]
Yeah, each server is gonna do autoupdate in the background.

To have up to date image you just need to rebuild it.

Hope that answers your question.

**Comment by janstuemmel** [comment]
thanks!
