### ISSUE TITLE
32bit issue

### ISSUE THREAD

**Issue by cgarnier** [Gonzih/docker-csgo-server#6]
Hello, 
I got this error:
```
dlopen failed trying to load:
/home/csgo/.steam/sdk32/steamclient.so
with error:
/home/csgo/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory

```

**Comment by Gonzih** [comment]
Hi, wanna provide some extra info? Like environment details, etc?

**Comment by cgarnier** [comment]
```
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ uname -a
Linux dev3 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

On which kernel are you running it ?

**Comment by Gonzih** [comment]
I just run the container and saw similar error, but server seems to be 
running fire. Can you confirm that server is running and this is just a 
warning?

**Comment by cgarnier** [comment]
It seams runing but i dont think it s the case. I wasnt able to connect on it yesterday. I will retry this evening.

Maybe you can add this line after the build 
`ln -s /home/csgo/hlserver/linux32 /home/csgo/.steam/sdk32`

**Comment by cgarnier** [comment]
I try that this evening. I keep you in touch

**Comment by Gonzih** [comment]
Cool, thanks!

**Comment by cgarnier** [comment]
In fact that was not the issue. I was unable to connect to it because i forgot the +set_steamaccount param.
Maybe you could add some doc about it ?

Steam stuff is weird, there is errors in the logs but it s working -_-'

**Comment by Gonzih** [comment]
Cool, glad to hear that it worked for you. Do you have link to 
steamaccount param somewhere in documentation that I can take look at? 
Idea of this container was to run anonymous server first, and later you 
should be able to reconfigure it in the way you want it to function.

**Comment by adrianlee** [comment]
Here's the documentation you're looking for.

**Registering Game Server Login Token**
https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers

For public server add +sv_setsteamaccount <token> -net_port_try 1 to use your GSLT.

**Comment by Gonzih** [comment]
Thanks @adrianlee, mentioned this in README.
