### ISSUE TITLE
Volumes and env

### ISSUE THREAD

**Issue by cgarnier** [Gonzih/docker-csgo-server#7]
Hello, 
Could be nice to add some volumes to the dockerfile.
/maps/custom
/cfg/custom

and an environment configuration to be able to easily configure the server on startup (tickrate, hostname, rcon_password ...)

**Comment by Gonzih** [comment]
You can add volumes already via -v /hostpath:/containerpath, you dont 
need VOLUME declracation inside the container. Im not into parsing env 
vars and generating config based on that, just use your own config and 
command line argument. Simplicity.

**Comment by cgarnier** [comment]
VOLUME is not an useless docker statement. It permit to docker to know what must be persisted. If you specify the module you can let docker deal with it. Else you have to use -v.

It s not in the docker spirit to have to setup something in the command or to have to manualy set the volumes.

**Comment by Gonzih** [comment]
PR is welcome.
